"""Research organization models and orchestration for the simulator."""

from independent_investment_agents.research.agents import ResearchOrganization
from independent_investment_agents.core import AgentRuntime, AgentRuntimeConfig, ErrorResult, TaskEnvelope, TaskQueue, TaskResult
from independent_investment_agents.research.llm_provider import LLMProvider, TemplateLanguageProvider
from independent_investment_agents.research.models import (
    AgentFinding,
    AgentRunContext,
    AgentRunResult,
    ChatResponse,
    DecisionContext,
    EvidenceRecord,
    KnowledgeMemory,
    ResearchTask,
)
from independent_investment_agents.research.repository import ResearchRepository
from independent_investment_agents.research.evidence_quality import (
    ArticleBodyFetcher,
    ArticleSummarizer,
    EvidenceQualityPolicy,
    HeadlineBodyMismatchChecker,
    MaterialityClassifier,
    NewsImpactScorer,
    ShortTermLongTermClassifier,
    SourceReliabilityTable,
)
from independent_investment_agents.research.scoring import MultiFactorScoringEngine, PositionSizingEngine, StopLossTakeProfitEngine
from independent_investment_agents.research.simulation_modes import BacktestMode, PaperLiveMode, ReplayMode, ManualResearchMode
from independent_investment_agents.research.symbol_queue import (
    SymbolProcessingPlan,
    SymbolProcessingStore,
    SymbolQueueRepository,
    SymbolRotationPolicy,
    build_symbol_processing_plan,
)
from independent_investment_agents.research.strategy_output import StrategyOutputEngine
from independent_investment_agents.research.trading_runtime import (
    AgentEvent,
    AgentRuntimeEngine,
    AgentRuntimeStore,
    AgentRuntimeState,
    AgentTask,
    SharedTradingContext,
    TradeProposal,
    TradingConsensus,
    build_shared_trading_context,
)
from independent_investment_agents.research.advanced_agents import (
    AgentScorecard,
    AgentSelfEvaluator,
    AgentTrustScoreManager,
    AgentVote,
    CommitteeDecision,
    DecisionPatternMemory,
    EnhancedRedTeamAgent,
    EvidenceReliabilityMemory,
    ExecutionReadinessAgent,
    FactorWeightProfileManager,
    FinalApprovalGate,
    FundamentalAnalystAgent,
    InvestmentCommittee,
    MarketStructureAgent,
    NewsReasoningAgent,
    OutcomeFeedbackApplier,
    PortfolioManagerAgent,
    SelfReflectionReport,
)

__all__ = [
    "AgentFinding",
    "ArticleBodyFetcher",
    "ArticleSummarizer",
    "AgentEvent",
    "AgentRuntimeEngine",
    "AgentRuntime",
    "AgentRuntimeConfig",
    "AgentRuntimeStore",
    "AgentRuntimeState",
    "AgentRunContext",
    "AgentRunResult",
    "AgentScorecard",
    "AgentSelfEvaluator",
    "AgentTask",
    "AgentTrustScoreManager",
    "AgentVote",
    "ChatResponse",
    "CommitteeDecision",
    "BacktestMode",
    "DecisionContext",
    "DecisionPatternMemory",
    "EnhancedRedTeamAgent",
    "EvidenceReliabilityMemory",
    "EvidenceRecord",
    "EvidenceQualityPolicy",
    "ErrorResult",
    "ExecutionReadinessAgent",
    "FactorWeightProfileManager",
    "FinalApprovalGate",
    "FundamentalAnalystAgent",
    "InvestmentCommittee",
    "KnowledgeMemory",
    "LLMProvider",
    "ManualResearchMode",
    "MarketStructureAgent",
    "MultiFactorScoringEngine",
    "NewsReasoningAgent",
    "OutcomeFeedbackApplier",
    "PaperLiveMode",
    "PortfolioManagerAgent",
    "PositionSizingEngine",
    "ReplayMode",
    "ResearchOrganization",
    "ResearchRepository",
    "ResearchTask",
    "SharedTradingContext",
    "SourceReliabilityTable",
    "SelfReflectionReport",
    "StrategyOutputEngine",
    "StopLossTakeProfitEngine",
    "SymbolProcessingPlan",
    "SymbolProcessingStore",
    "SymbolQueueRepository",
    "SymbolRotationPolicy",
    "TemplateLanguageProvider",
    "TaskEnvelope",
    "TaskQueue",
    "TaskResult",
    "TradeProposal",
    "TradingConsensus",
    "build_symbol_processing_plan",
    "build_shared_trading_context",
    "HeadlineBodyMismatchChecker",
    "MaterialityClassifier",
    "NewsImpactScorer",
    "ShortTermLongTermClassifier",
]
